apiVersion: apps/v1
kind: Deployment

metadata:
  name: canary-demo-v1-deployment
  labels:
    app: canary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-demo

  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
        - name: canary-demo-v1
          image: nginx #version-1
      
      
