apiVersion: apps/v1
kind: Deployment

metadata:
  name: canary-demo-v2-deployment
  labels:
    app: canary-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: canary-demo

  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
        - name: canary-demo-v2
          image: httpd #version-2

      
      
